service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: handlers/getProductsById.handler
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
