service: import-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource:
            - ${env:BUCKET_ARN}
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - ${env:BUCKET_ARN}/*

functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                name: true
